#!/bin/csh -f 

# Set the location of the system to help in configuring the machine names.
# The location is simply a 2-character code stored in the '_location' file
# in the top directory, values may be:
#
#	"CR"		=> Tucson Clean Room
#	"FR"		=> Tucson Flex Rig
#	"KP"		=> KPNO 4-meter
#	"CT"		=> CTIO 4-meter
#

setenv USER_DISPLAY 	$DISPLAY
setenv RTD		fast:inet:3200

set SUP_LOG = /dhs/test//sup.log
set PAN_LOG = /dhs/test/pan.log
set DCA_LOG = /dhs/test/dca.log
set NOC_LOG = /dhs/test/noc.log
set COL_LOG1 = /dhs/test/col1.log
set COL_LOG2 = /dhs/test/col2.log
set SMC_LOG = /dhs/test/smc.log
set PXF_LOG = /dhs/test/pxf.log

/dhs/util/stopdhs
rm -rf $SUP_LOG $PAN_LOG $DCA_LOG $NOC_LOG $COL_LOG1 $COL_LOG2 $SMC_LOG $PXF_LOG

#Pseudo Hosts


#-------------------------------------------------------------------------------



echo "Cleaning up...."
echo ""

    if (`uname -s` == "Darwin") then
        set pflags = "-augxww"
    else
        set pflags = "-efw"
    endif
    set pfiles = "/tmp/pvm*50*"

    echo halt | $PVM_ROOT/lib/pvm 						>& /dev/null
    /bin/rm -f $pfiles 						>& /dev/null

    echo conf | $PVM_ROOT/lib/pvm 
    echo ""

    /dhs/smclean
	  

echo "Re-Starting VNC for DHS...."
echo ""
    vncserver -kill :1						>& /dev/null
    vncserver -geometry 1280x1024 -depth 8 -cc 3		>& /dev/null

    echo "Starting VNC viewer...."
    (vncviewer -passwd ~/.vnc/passwd -display $USER_DISPLAY :1	>& /dev/null &)

echo "Starting DHS...."
echo ""

setenv DISPLAY :1
set    XTERM	= "xterm -fn fixed"
#set    XTERM1	= "xterm -fn fixed -iconic "
#
set    XTERM1	= "xterm -fn fixed "

##--------------
## Collectors
##--------------
echo "Starting Collectors...."
echo ""

(sleep  4; $XTERM1 -geometry 80x20+100+350 -e "echo `date` Starting >! $COL_LOG1 ; /dhs/bin/collector -console -mbus -host nfdhs_01 -port 4575 -debug 60 -id NOCS |& tee -a $COL_LOG1 ; echo `date` Exitting >> $COL_LOG1 ; sleep 30 &" ) &


(sleep  6; $XTERM1 -geometry 80x20+200+400 -e "echo `date` Starting >! $COL_LOG2; /dhs/bin/collector -console -mbus -host nfdhs_01 -port 4576 -debug 60 -id PanA |& tee -a $COL_LOG2; echo `date` Exitting >> $COL_LOG2 ; sleep 30 &" ) &

##--------------
## SMC Managers
##--------------
echo "Starting Managers...."
echo ""

(sleep 10; $XTERM1 -geometry 80x20+200+450 -e "/dhs/bin/smcmgr -console -host nfdhs_01 -mbus -dev $RTD -debug 60 |& tee -a $SMC_LOG ; sleep 30 & ") &


##--------------
## PXF
##--------------
echo "Starting PXF...."
echo ""

(sleep 14; $XTERM1 -geometry 80x20+200+500 -e "/dhs/bin/pxf -console -host nfdhs_01 -mbus -debug 60  |& tee -a $PXF_LOG ; sleep 30 &" ) &


##--------------
## DCA
##--------------
echo "Starting DCA...."
echo ""

(sleep 20; $XTERM -geometry 80x20+645+360 -e /"dhs/mosdca/mosdca -host nfdca -debug 2 -reqlevel 2 -vminit cachesize=312m -imformat %N -maxgkw 2048 -maxikw 2048 -dir /home/data -ktm /dhs/lib/newfirm.tcl |& tee -a $DCA_LOG ; sleep 30 &" ) &


if ( 0 ) then
##--------------
## NOCS/Pan Clients
##--------------
echo "Starting Pan Client...."
echo ""

setenv MONSOON_DHS "127.0.0.1:4150"
(sleep 5; $XTERM -geometry 80x12+300+720 -e "echo `date` Starting >! $PAN_LOG ; /dhs/test/pan  -sim -debug 0 -host nfpan_a -A  |& tee -a $PAN_LOG ; echo `date` Exitting >> $PAN_LOG ; sleep 30 &") &

echo "Starting NOC/Pan Clients...."
echo ""

setenv MONSOON_DHS "127.0.0.1:4150"
(sleep 6; $XTERM -geometry 80x12+100+720 -e "echo `date` Starting >! $NOC_LOG ;/dhs/test/nocs -sim -debug 0 -host newfirm -interactive |& tee -a $NOC_LOG ; echo `date` Exitting >> $NOC_LOG ; sleep 30 &")  &

setenv MONSOON_DHS ""

endif
##--------------
## Supervisor
##--------------
echo "Starting Supervisor...."
echo ""

exec $XTERM -geometry 80x22+645+40 -e "/dhs/dhssup/super -port 4150 -host newfirm -console -config /dhs/test/config-newfirm.sim -nclients 8 -geometry 640x640+0+40  |& tee -a $SUP_LOG"


echo "All done"
echo ""
